schema_version = "1.0.0"
id = "tobins_enhanced_pie"
version = "1.0.0"
name = "Tobin's Enhanced Pie Menu"
tagline = "Useful pie menus for common activities"
maintainer = "Tobin Cavanaugh <tobincavanaugh@gmail.com>"
type = "add-on"
website = "https://github.com/ninofiliu/blender-ambientcg-addon"
tags = ["Import-Export", "Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
network = "Makes calls to AmbientCG"
files = "Import and cache textures to disk"