schema_version = "1.0.0"
id = "tobins_enhanced_pie"
version = "1.0.0"
name = "Tobin's Enhanced Pie Menu"
tagline = "Useful pie menus for common activities"
maintainer = "Tobin Cavanaugh <tobincavanaugh@gmail.com>"
type = "add-on"
website = "https://github.com/TobinCavanaugh/TobinsEnhancedPieMenus"
tags = ["User Interface"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
